### ISSUE TITLE
Implement custom fields per disk.

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/files-module#7]
In old pyro it was possible to add meta data to a file (for example, alt image and tags) and it was also possible to replace the image for a given file.  Is there a plan to add this functionality?  

Ideally it would be nice to take things even further and allow per-disk field sets.  So, for example, if i create a disk called "my-disk" i would have the ability to associate custom fields with that disk so that whenever a user went to add a file to that disk, the additional fields would be available.  

An example use case might be associating photos with a property and selecting one as primary which would require:

1. boolean field type for "is primary"
2. description wysiwy
3. title

when used in conjuction with the multiple files field type a user could drag a bunch of photos for a property into the uploader and take care of all the photos uploads at once, then go back over the uploaded files and additional info.

the only other way to handle this (at least as efficiently as mentioned above) would be to create a custom field type that duplicated the multiple file upload functionality and then building on top of it so other fields can be associated with a given image.

here's an example of what i'm referring to from old pyro (using a custom field type i created):

https://www.evernote.com/l/ARErX6B0pOJJoZSG2QK0ik_oDvGoKR8vGlI

**Comment by RyanThompson** [comment]
Hey Matt! While I do plan on adding a couple additional fields (alt, tags and description likely) I don't think the files module is an appropriate spot for that.

I am soon adding sorting support to the multiple files field type so you could use the first one as primary. And most the modules now have custom fields so you can add your own fields easily.

This would also be a PERFECT scenario for the grid field type which would is going to be considerably easier to build this time around. Like.. ridiculously easier.

I want to keep core files things pretty true to their core values. Managing files.

I do want to add more role based access control to files module though - you have any input on that? I was thinking disks only but idk..

**Comment by mattcdavis1** [comment]
ok cool - yeah i guess title / caption would be adequate for 95% use cases (although the per-file field association is offered by other cms's so pyro would be a bit less flexible out of the box in comparison). 

for permissions - i would think disks would probably be enough but could possible see directory permissions being helpful.  I suppose you could always just create multiple disks with the same settings to accomplish the same thing but ideally it would be nice to have directory level also.  

for example, we usually create a single s3 disk (location in old pyro) for all user content but could see clients potentially wanting to limit permissions at a directory level for some of their users.

overall, we don't get a whole lot of demand for fine grained permissions although we have been getting more requests for this type of thing recently with some of our larger clients.

**Comment by RyanThompson** [comment]
Can you point me in the direction of a CMS that offers per file field association out of the box? Most all CMSs I've seen hardly have a decent field type layer in general so I'd be curious to see this kinda thing and how they implement it.

It would be easy to do for sure - it's just a matter of if it's the right thing to do or not. Sometimes just because you can doesn't mean you should ^_^

Ya I think folder permissions - while perhaps used less will be helpful in those clutch instances.

**Comment by mattcdavis1** [comment]
yeah sure - here's a screenshot and link:

Field Setup:

https://www.evernote.com/l/ARGcT36qrctL4JGUEY25bUnBu5daOjJ3ois
https://www.evernote.com/l/ARGXbtl1L3RJq73gZHVLjmF5yyKnvqrIv3g

Field Rendered (i just used some random fields in this case):

https://www.evernote.com/l/ARHzqcVr9UpOf7_SbRg2DIjgWVOjDsORvrE

CMS Link:

https://buildwithcraft.com/

**Comment by RyanThompson** [comment]
Arg.. you would send me an example of Craft. I'm sold. Touché!

**Comment by RyanThompson** [comment]
I'm afraid I've jumped the gun previously.. I've been really stewing on this..

So I've been discussing this a bit @mattcdavis1 with some other peers. Can you explain to me (if any) a use case where this kind of functionality would be not possible with PyroCMS as it sits? 

I understand the concept of out of the box.. But, especially with the Streams module. This would be adding unnecessary clutter to the files module. IMO it should be dumb, with tight integration.

If you want to add a listing of property images, spin up a stream or integrate it into your module.

If I can see / be convinced where this is a problem for PyroCMS and this feature will add both quality and value to the CMS as a whole.. I think I'd do it. But the files module is for files management. And files don't have lots of meta. A stream using files would though.

Hopefully this makes sense!

Let me know your thoughts.

**Comment by RyanThompson** [comment]
Also, a grid field type would solve this in the MOST elegant manner I think too.

**Comment by mattcdavis1** [comment]
well - the only downside to the grid field type approach is that you couldn't upload all the files at the same time like you could for a multiple image field type.  you would have to click a plus button for each one.  We've had requests from multiple clients for the ability to upload multiple files at the same time for photo galleries.  

So yeah - grid would accomplish the same thing but not sure that it would do it in the most elegant  / efficent manner for a photo slider scenario.  I guess another option would be to add additional functionality at the multiple files field type level rather than at the disk level.

**Comment by RyanThompson** [comment]
In the event of additional fields though you're going to need to revisit each file anyways to set any additional information. 

And perhaps gallery images are a bad example because those really wouldn't have any additional information either right?? I can tell you now that it'd be a bit (3.1) until I would support the additional meta on the files upload form from the files field type. There are other details to get to. But if it makes sense I could meet you in the middle and support what you're saying and you could fork the files field type and add in the support for that (probably using the ajax form option). 

I'm close. I really don't want to overcomplicate a good thing is all. Ill have to look through some of my own clients al little more and see how I'd use it in those cases perhaps.

Generally though I feel like I would implement a block even for instances like this where an image is meant to be used with additional information.

**Comment by RyanThompson** [comment]
Would your end user use this with the files field type / file field type or in the files module itself?

**Comment by mattcdavis1** [comment]
for us the use case would generally be in the context of a stream [as shown in the first example above](https://www.evernote.com/l/ARErX6B0pOJJoZSG2QK0ik_oDvGoKR8vGlI)  (rather than the files module).  and yeah - i understand that they would have to revisit the files anyway in most cases but:

1. in spite of that we've still gotten requests for this - it's still kind of nice to be able to handle the file upload portion all at one time then go back over and add information.

2. in the case of adding a boolean flag (or any other optional field) you wouldn't necessarily need to revisit all the files.  I realize that using the first file as the "featured" could work but there might be scenarios where you want the first file and the featured file to be different.

maybe this could just be functionality for a premium version of the multiple files field type or something.

**Comment by RyanThompson** [comment]
Sorry man - I've decided against this one. For what it's worth here are my thoughts on it:

Streams fields and customization thereof for a module should DIRECTLY support the core intentions of that module. Adding custom fields to the files module would be pushing it towards something it is not. In the case of Posts or Pages for instance though, it's in direct alignment with the core intentions of the module. The files module is the backbone engine for managing files in a Streams Platform environment. Not necessarily something to manage front facing rich content.

The Grid field type will wrap this kind of UI and functionality better and in a broader scope. Allowing the integration of custom fields to be closer to where it's needed in your business logic (instead of in an imposter module likes Files + custom fields).

You could wrap the existing files module OR files-field_type (better option IMO) in your own version or fork it and add the functionality (it's MIT).

I hope this helps shed some light on the decision!

Ryan

**Comment by mattcdavis1** [comment]
ok cool - yeah i'll probably just add this functionality to the multiple files field type.  For the grid field type - are you planning on matching functionality of Craft's matrix or will this be more similar to the expression engine grid field (where all the fields are horizontally displayed and each row always has the same field set)?  If the latter, do you have anything planned that would match the functionality of Craft's matrix field type?

**Comment by RyanThompson** [comment]
Can you tell me a little more about the Matrix field type? Never used it before.

**Comment by mattcdavis1** [comment]
sure - the matrix field type is pretty much the killer feature for Craft and whenever i have conversations about Craft vs Pyro that is the first thing that comes up in conversations.  before pixel and tonic created their own cms they had a matrix field type for Expression Engine that is comparable to the current grid field in Expression Engine.  It added alot of flexibility but was still somewhat limited. 

When Craft created their own CMS they added functionality which allowed you to basically add / reorder multiple different preconfigured fieldsets within the context of a post (see screenshot below).  they also dropped the horizontal layout (which only allows for a couple of fields before things start getting squished) in favor of a vertical fieldset.  So for example, if a fieldset has 10 fields, that's no problem.  Here are some screenshots to illustrate what i'm talking about:

https://www.evernote.com/l/ARH5aQMJBadMhIMdtqkLbl-D6M5JX2vNy1c

if you look at the bottom where the arrows are, each one of those buttons represents a fieldset.  So the "Article Body" is a single field which may have any combination of fieldsets (which can also be sorted).  In one post, i might want a quote and a video.  in another, i might want a wysiwyg and and inline image.  The matrix field type allows for this flexibility.  as well as for changing the position of these items within the post.  with a traditional grid field type, you would not have this flexibilty.  the fieldsets would be fixed beforehand.

here's an example of the ui for creating a matrix field type:

https://www.evernote.com/l/ARFhCINimalNO4mntwGH-JesnRIyE7GUOgg

the matrix field shown above has 8 field sets and the fieldset shown in the screen shot has two fields (file and caption).  This allows for tons of flexibility for clients while still allowing developers alot of control in how stuff is displayed (since the data is stored in fields as opposed to trying to have the clients do all this in a wysywig)

**Comment by RyanThompson** [comment]
That's pretty cool - I would like land in a happy medium. Seems like they've shoved a ton of flexibility into that one field type instead of in their modules. That same end result is 100% doable but seems a bit more manageable IMO in PyroCMS. 

In PyroCMS there are different post types - which would be like your field set in the matrix field type. But post types (or page types) have separate layout / styling / control entirely as well as different field sets / validation / etc. Then when you add a grid field type and it's sub-stream entries you don't have to worry about that single grid field type basically doing everything the module is supposed to do. (If I understand what you're showing me).

So you would have 8 post types (caption, image, gallery, default, etc for instance). And any other those could have any number of fields, layouts, styling, etc as well as grid field types. Not one post type and 8 grid sets in 1 field.

As your UI goes its not so smashed into 1 thing either - when creating a new post / page it asks what kind you want to create - and shows you only what you need to create that one - it doesn't give you the gamut. This can easily be replicated in your own modules too and I will likely be pushing that common UI logic into core before long.

Same effect - different approach. Even if I do say so myself, and I do, I think I would prefer a better module over an ultra-zord like field type. 

To answer some of your other questions though - grid will be horizontal like normal form layout and will likely add internal panels to it's section - tabbed or not. Everything overridable you would be able to define your own layout and damn near anything else to better nail down your end product.

And the field type will have it's own management UI similar to building other stream sets in PyroCMS.

**Comment by mattcdavis1** [comment]
right - but there are a number of disadvantages to the approach you are describing (at least as i understand and based on playing around with the current posts module).

1. end users can't sort different post types within the context of a single post.  for example, in one post the end user might want the inline image first above the wysiwig.  in the next post, vice versa.  

2. the fieldsets are fixed beforehand.  with matrix, the fieldsets are just available and may or may not be used.  this gives the user much more control.

3. you can't add multiple fieldsets within a single post.  each post is it's own fieldset.  Maybe for one post a user wants to add two twitter cards and three inline images, and the next 1 wysiwyg and two photo galleries.

I've pretty much planned on building this out myself so no big deal but i disagree that the current pyro approach is better / more flexible.  It's great for what it is but it does not provide the degree of control / flexibility for end users that a matrix field type does.

**Comment by RyanThompson** [comment]
Well.. On a smaller scale that makes a bit more sense with the Grid / Matrix field type handling that. My brain went instantly to "remake post types using a field type" lol. So I could see there being benefit there.

As with all of the stuff I do here it's not a problem to build in the functionality. It's just a matter of if it helps / clutters in the long run. 

I think this one helps when thinking about it in a simpler light. Ill plan on multiple grid types per field.

Can you tell me - do they create a table for each one as well and treat each field set as a table / "stream"?

**Comment by mattcdavis1** [comment]
yes - they do create a separate table for each matrix field type.  so in pyro terms, yeah each matrix field would be like it's own stream.

**Comment by mattcdavis1** [comment]
on a somewhat related note - if all streams were created with a uuid column (and populating / providing access to that was handled by pyro) that would be really helpful for advanced field types like this because you could handle all the relationships based on the uuid (which you would know before the record was created).  

that would mean the form fields could have the relational value in the fields even on the create form.  for example:

`input[my_main_entry_uuid][my_matrix_fieldname][my_matrix_field_type][]`

as opposed to

`input[{dont_know_what_goes_here_yet_so_processing_is_more_complicated}][my_matrix_fieldname][my_matrix_field_type][]`

**Comment by RyanThompson** [comment]
Streams all have their own tables too and it's baked in pretty deep.

Regarding the fields in the form - they are also prefixed (multiple forms) and suffixed (translations). In the case of the grid field type your field names would like look like this {prefix}field_slug[grid_field_slug][]

Just off the top of my head - the grid field type will be self handling for sure - which means it will handle it's own saving of its entries. And have it's own validator which validates internal streams based on their config while min & max nodes / required or not / etc would be handled by the parent form using normal validation.

It's all very systematic so I don't foresee any issues. Sounds like fun!

**Comment by RyanThompson** [comment]
All goes right, and it has so far.. You should be able to have translatable grids with translatable fields and still use epic tools like the multiform builders!

**Comment by mattcdavis1** [comment]
great!  can't wait to try it out once it's ready.
